apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: mq-event-listener
  name: mq-event-listener
  namespace: mq01-ci
spec:
  description: |
    Choose what pipeline to run by setting the template name.
    Either mq-trigger-template or mq-externals-trigger-template
  serviceAccountName: pipeline
  triggers:
  - name: mq-trigger
    interceptors:
      - ref:
          name: "cel"
        params:
        - name: "filter"
          value: "header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/main' && body.repository.full_name == 'jborg-barbesatibm/.mq01-src'"
    bindings:
      - ref: mq-trigger-binding
    template:
      ref: mq-externals-trigger-template
