apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: mq-dev-pipeline-run-
  namespace: mq01-ci
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: mq-dev-pipeline
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-creds
    secret:
      secretName: mq01-git-credentials
  params:
  - name: source-repo-url
    value: https://github.com/jborg-barbesatibm/.mq01-src.git
  - name: revision
    value: "9965123472307a6b5d1133848b2cfdf86fb1542b"
  - name: dockerfile
    value: $(workspaces.source.path)/repo/main/bin/Dockerfile
  - name: ops-repo-url
    value: https://github.com/jborg-barbesatibm/mq01-ops.git
  - name: image-reference
    value: image-registry.openshift-image-registry.svc:5000/mq01-ci/mq01
  - name: storage-driver
    value: vfs
  - name: tls-verify
    value: "false"
  - name: git-user-name
    value: "jbarbes"
  - name: git-user-email
    value: "barbes@dk.ibm.com"

